spring.application.name=SpringBoot_Mybatis_demo

# 配置数据库连接
# 数据库连接池配置
# 默认使用的是HikariCP连接池(如果想换成Druid连接池,需要在pom.xml中添加Druid连接池依赖,并配置以下属性)
spring.datasource.type=com.alibaba.druid.pool.DruidDataSource
spring.datasource.url=jdbc:mysql://localhost:3306/jdbc_learning
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=123456

#mybatis的配置日志输出到控制台
mybatis.configuration.log-impl=org.apache.ibatis.logging.stdout.StdOutImpl

# 配置mybatis的xml映射文件（如果不按mybatis的默认规则，需要配置以下属性）
#mybatis.mapper-locations=classpath:mapper(包名)/*.xml
