spring:
  application:
    name: tlias_web_management
    # 数据库配置
  datasource:
    url: jdbc:mysql://localhost:3306/tlias
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
#      # 配置数据库连接池（不配置用默认的）
#      type: com.alibaba.druid.pool.DruidDataSource


  servlet:
    multipart:
      # 配置上传文件的最大大小（单个文件大小）
      max-file-size: 10MB
      # 配置上传文件的最大请求大小（总上传文件大小不能超过该值）
      max-request-size: 100MB


mybatis:
  # 配置mybatis的xml映射文件（如果不按mybatis的默认规则，需要配置以下属性）
  #mapper-locations: classpath:mapper/*.xml

  # 配置mybatis日志配置
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # 配置mybatis开启驼峰命名(推荐)
#    驼峰命名规则：   abc_xyz    =>   abcXyz
#    - 表中字段名：abc_xyz
#    - 类中属性名：abcXyz
    map-underscore-to-camel-case: true

#spring事务管理日志
logging:
  level:
    org.springframework.jdbc.support.JdbcTransactionManager: debug

#阿里云OSS
aliyun:
  oss:
    endpoint: https://oss-cn-beijing.aliyuncs.com
    bucketName: javaweb-tlias521
    region: cn-beijing